/* tslint:disable */
/* eslint-disable */
/**
 * Swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessengerDTO } from './MessengerDTO';
import {
    MessengerDTOFromJSON,
    MessengerDTOFromJSONTyped,
    MessengerDTOToJSON,
    MessengerDTOToJSONTyped,
} from './MessengerDTO';

/**
 * 
 * @export
 * @interface MessengerGetMessengersResponseDTO
 */
export interface MessengerGetMessengersResponseDTO {
    /**
     * 
     * @type {Array<MessengerDTO>}
     * @memberof MessengerGetMessengersResponseDTO
     */
    messengers: Array<MessengerDTO>;
}

/**
 * Check if a given object implements the MessengerGetMessengersResponseDTO interface.
 */
export function instanceOfMessengerGetMessengersResponseDTO(value: object): value is MessengerGetMessengersResponseDTO {
    if (!('messengers' in value) || value['messengers'] === undefined) return false;
    return true;
}

export function MessengerGetMessengersResponseDTOFromJSON(json: any): MessengerGetMessengersResponseDTO {
    return MessengerGetMessengersResponseDTOFromJSONTyped(json, false);
}

export function MessengerGetMessengersResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessengerGetMessengersResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'messengers': ((json['messengers'] as Array<any>).map(MessengerDTOFromJSON)),
    };
}

  export function MessengerGetMessengersResponseDTOToJSON(json: any): MessengerGetMessengersResponseDTO {
      return MessengerGetMessengersResponseDTOToJSONTyped(json, false);
  }

  export function MessengerGetMessengersResponseDTOToJSONTyped(value?: MessengerGetMessengersResponseDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messengers': ((value['messengers'] as Array<any>).map(MessengerDTOToJSON)),
    };
}

