/* tslint:disable */
/* eslint-disable */
/**
 * Swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessengerDTO
 */
export interface MessengerDTO {
    /**
     * 
     * @type {string}
     * @memberof MessengerDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof MessengerDTO
     */
    label: string;
    /**
     * 
     * @type {Date}
     * @memberof MessengerDTO
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the MessengerDTO interface.
 */
export function instanceOfMessengerDTO(value: object): value is MessengerDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function MessengerDTOFromJSON(json: any): MessengerDTO {
    return MessengerDTOFromJSONTyped(json, false);
}

export function MessengerDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessengerDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'label': json['label'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

  export function MessengerDTOToJSON(json: any): MessengerDTO {
      return MessengerDTOToJSONTyped(json, false);
  }

  export function MessengerDTOToJSONTyped(value?: MessengerDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'label': value['label'],
        'createdAt': ((value['createdAt']).toISOString()),
    };
}

