/* tslint:disable */
/* eslint-disable */
/**
 * Swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageDTO } from './MessageDTO';
import {
    MessageDTOFromJSON,
    MessageDTOFromJSONTyped,
    MessageDTOToJSON,
    MessageDTOToJSONTyped,
} from './MessageDTO';

/**
 * 
 * @export
 * @interface MessengerGetMessagesResponseDTO
 */
export interface MessengerGetMessagesResponseDTO {
    /**
     * 
     * @type {Array<MessageDTO>}
     * @memberof MessengerGetMessagesResponseDTO
     */
    messages: Array<MessageDTO>;
}

/**
 * Check if a given object implements the MessengerGetMessagesResponseDTO interface.
 */
export function instanceOfMessengerGetMessagesResponseDTO(value: object): value is MessengerGetMessagesResponseDTO {
    if (!('messages' in value) || value['messages'] === undefined) return false;
    return true;
}

export function MessengerGetMessagesResponseDTOFromJSON(json: any): MessengerGetMessagesResponseDTO {
    return MessengerGetMessagesResponseDTOFromJSONTyped(json, false);
}

export function MessengerGetMessagesResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessengerGetMessagesResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'messages': ((json['messages'] as Array<any>).map(MessageDTOFromJSON)),
    };
}

  export function MessengerGetMessagesResponseDTOToJSON(json: any): MessengerGetMessagesResponseDTO {
      return MessengerGetMessagesResponseDTOToJSONTyped(json, false);
  }

  export function MessengerGetMessagesResponseDTOToJSONTyped(value?: MessengerGetMessagesResponseDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messages': ((value['messages'] as Array<any>).map(MessageDTOToJSON)),
    };
}

