/* tslint:disable */
/* eslint-disable */
/**
 * Swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessengerCreateConversationResponseDTO
 */
export interface MessengerCreateConversationResponseDTO {
    /**
     * 
     * @type {string}
     * @memberof MessengerCreateConversationResponseDTO
     */
    messengerId: string;
}

/**
 * Check if a given object implements the MessengerCreateConversationResponseDTO interface.
 */
export function instanceOfMessengerCreateConversationResponseDTO(value: object): value is MessengerCreateConversationResponseDTO {
    if (!('messengerId' in value) || value['messengerId'] === undefined) return false;
    return true;
}

export function MessengerCreateConversationResponseDTOFromJSON(json: any): MessengerCreateConversationResponseDTO {
    return MessengerCreateConversationResponseDTOFromJSONTyped(json, false);
}

export function MessengerCreateConversationResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessengerCreateConversationResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'messengerId': json['messengerId'],
    };
}

  export function MessengerCreateConversationResponseDTOToJSON(json: any): MessengerCreateConversationResponseDTO {
      return MessengerCreateConversationResponseDTOToJSONTyped(json, false);
  }

  export function MessengerCreateConversationResponseDTOToJSONTyped(value?: MessengerCreateConversationResponseDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messengerId': value['messengerId'],
    };
}

