/* tslint:disable */
/* eslint-disable */
/**
 * Swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessengerSendMessageToAssistantBodyDTO
 */
export interface MessengerSendMessageToAssistantBodyDTO {
    /**
     * 
     * @type {string}
     * @memberof MessengerSendMessageToAssistantBodyDTO
     */
    message: string;
}

/**
 * Check if a given object implements the MessengerSendMessageToAssistantBodyDTO interface.
 */
export function instanceOfMessengerSendMessageToAssistantBodyDTO(value: object): value is MessengerSendMessageToAssistantBodyDTO {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function MessengerSendMessageToAssistantBodyDTOFromJSON(json: any): MessengerSendMessageToAssistantBodyDTO {
    return MessengerSendMessageToAssistantBodyDTOFromJSONTyped(json, false);
}

export function MessengerSendMessageToAssistantBodyDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessengerSendMessageToAssistantBodyDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

  export function MessengerSendMessageToAssistantBodyDTOToJSON(json: any): MessengerSendMessageToAssistantBodyDTO {
      return MessengerSendMessageToAssistantBodyDTOToJSONTyped(json, false);
  }

  export function MessengerSendMessageToAssistantBodyDTOToJSONTyped(value?: MessengerSendMessageToAssistantBodyDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

