/* tslint:disable */
/* eslint-disable */
/**
 * Swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserCreateUserBodyDTO
 */
export interface UserCreateUserBodyDTO {
    /**
     * 
     * @type {string}
     * @memberof UserCreateUserBodyDTO
     */
    name: string;
}

/**
 * Check if a given object implements the UserCreateUserBodyDTO interface.
 */
export function instanceOfUserCreateUserBodyDTO(value: object): value is UserCreateUserBodyDTO {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UserCreateUserBodyDTOFromJSON(json: any): UserCreateUserBodyDTO {
    return UserCreateUserBodyDTOFromJSONTyped(json, false);
}

export function UserCreateUserBodyDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCreateUserBodyDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

  export function UserCreateUserBodyDTOToJSON(json: any): UserCreateUserBodyDTO {
      return UserCreateUserBodyDTOToJSONTyped(json, false);
  }

  export function UserCreateUserBodyDTOToJSONTyped(value?: UserCreateUserBodyDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

