/* tslint:disable */
/* eslint-disable */
/**
 * Swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserCreateUserResponseDTO
 */
export interface UserCreateUserResponseDTO {
    /**
     * 
     * @type {string}
     * @memberof UserCreateUserResponseDTO
     */
    sessionId: string;
}

/**
 * Check if a given object implements the UserCreateUserResponseDTO interface.
 */
export function instanceOfUserCreateUserResponseDTO(value: object): value is UserCreateUserResponseDTO {
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    return true;
}

export function UserCreateUserResponseDTOFromJSON(json: any): UserCreateUserResponseDTO {
    return UserCreateUserResponseDTOFromJSONTyped(json, false);
}

export function UserCreateUserResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCreateUserResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionId': json['sessionId'],
    };
}

  export function UserCreateUserResponseDTOToJSON(json: any): UserCreateUserResponseDTO {
      return UserCreateUserResponseDTOToJSONTyped(json, false);
  }

  export function UserCreateUserResponseDTOToJSONTyped(value?: UserCreateUserResponseDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessionId': value['sessionId'],
    };
}

